version: "3.7"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - iz_data
    volumes:
      - ./volumes/iz-mysql-data:/var/lib/mysql:rw
      - ./volumes/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./volumes/iz-mysql-config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment: 
      MYSQL_ROOT_PASSWORD: 2}d5^1[A6f1%
      MYSQL_DATABASE: iz_data

  data:
    build: 
      context: './services/data_service'
      dockerfile: Dockerfile
    networks:
      - iz_data
      - iz_data_api
    environment: 
      NODE_ENV: production
    depends_on: 
      - mysql
    
  frontend:
    container_name: "strona_www"
    volumes:
      - './frontend_php/src:/var/www/app/'
    image: romeoz/docker-apache-php
    networks:
      - iz_net
    ports:
      - "80:80"
    
  api:
    build:
      context: './api'
      dockerfile: Dockerfile
    networks:
      - iz_net
      - iz_data_api
    ports:
      - "4000:4000"
    environment: 
      NODE_ENV: production

networks:
  iz_net:
    driver: bridge
  iz_data:
    driver: bridge
  iz_data_api:
    driver: bridge
volumes:
  iz-mysql-data:
  iz-store: