services:
  data:
    build: 
      context: https://github.com/Antaresque/docker_serwis.git#:services/data_service
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: https://github.com/Antaresque/docker_serwis.git#:frontend
    ports:
      - "80:80"
